### ISSUE TITLE
Doesn't support static kernels

### ISSUE THREAD

**Issue by pkubaj** [desultory/ugrd#81]
I have my kernel built fully static, without any modules and without support for loading modules. When I try to build initramfs with ugrd, I'm getting:
```
ERROR    | Kernel module directory does not exist for kernel: 6.6.52-gentoo
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/ugrd/main.py", line 60, in main
    generator.build()
  File "/usr/lib/python3.12/site-packages/ugrd/initramfs_generator.py", line 78, in build
    self.run_hook(hook)
  File "/usr/lib/python3.12/site-packages/ugrd/initramfs_generator.py", line 120, in run_hook
    if function_output := self.run_func(function, *args, **kwargs):
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ugrd/initramfs_generator.py", line 89, in run_func
    if function_output := function(self):
                          ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ugrd/kmod/kmod.py", line 174, in get_kernel_metadata
    raise DependencyResolutionError(f"Kernel module directory does not exist for kernel: {self['kernel_version']}")
ugrd.kmod.kmod.DependencyResolutionError: Kernel module directory does not exist for kernel: 6.6.52-gentoo
```

This is on ugrd 1.20.0 (Gentoo stable).

**Comment by desultory** [comment]
Using the `no_kmod` option should allow this, if not there is a bug with it. You can set `no_kmod = true` in /etc/ugrd/config.toml

**Comment by pkubaj** [comment]
Yes, that helps, thanks.
