### ISSUE TITLE
bcachefs support

### ISSUE THREAD

**Issue by alexminder** [desultory/ugrd#84]
Add bcachefs rootfs support please.

bcachefs have features wich can be used in initrd:
- multiple devices, nount looks like `/dev/sdc:/dev/sdb:/dev/sda on MOUNTPOINT type bcachefs`;
- encryption as LUKS alternative;
- subvolumes, snapshots (boot from another root snapshot or subvolume)

**Comment by alexminder** [comment]
There is interesting hook for dracut to checking, if bcachefs device complete:

https://github.com/kode54/dracut-hook-bcachefs/tree/main

**Comment by desultory** [comment]
I briefly looked into this, I think the main issue I found was the source device notation bcachefs uses. Do you know if that's used by any other system? I'm wondering if I should make it more generic or make a separate parsing method for bcachefs. I've found most common filesystems use `slaves` in the /sys info for the device.

https://github.com/desultory/ugrd/blob/main/src/ugrd/fs/mounts.py#L215

It does simple parsing by reading /proc/mounts and splitting it, it will see `/dev/sdc:/dev/sdb:/dev/sda` as the "device" and im not sure if that will potentially break anything. If bcachefs has userspace stuff which just handles this, it's not a big deal, but currently ugrd tries to resolve UUID information (by default) to be later used to mount the correct device. At the least this would have to be disabled for bcachefs, especially with multidevice.

With btrfs multidevice, you  can just `btrfs device scan` then mount one of them by uuid, and it mounts the whole set. I don't really see how that module handles encryption or multidevice stuff, unless the bcachefs tools handle that transparently. https://github.com/kode54/dracut-hook-bcachefs/blob/main/bcachefs_finished.sh#L13

**Comment by alexminder** [comment]
> Do you know if that's used by any other system? 

As I know, no other. 

> With btrfs multidevice, you can just btrfs device scan then mount one of them by uuid, and it mounts the whole set.

From version 2.39 of libblkid it is possible to use UUID="", but with both of source notation systemd (mount generator) have problems.

> I've found most common filesystems use slaves in the /sys info for the device.

Yes, `/sys/fs/bcachefs/UUID/dev-N` are presented as slaves and inside this dirs links exists to real block devices.

The command `bcachefs show-super <DEVICE>` on any bcachefs device shows all the information about FS and all the slaves (how many slaves, external, internal UUIDs).

> If bcachefs has userspace stuff which just handles this,

`bcachefs` userspace utility from `bcachefs-tools` can do this.

>  I don't really see how that module handles encryption or multidevice stuff, unless the bcachefs tools handle that transparently.

This module don't check encryption. It is just try to mount it readonly. If one of slave not available mount will fail and process returns to initqueue for waiting. When udev enumerate all bcachefs type devices and `bcachefs_finished.sh` mounts success, then unmount and boot continues where itis possibe dracut to mount with UUID or `/dev/sdc:/dev/sdb:/dev/sda`  as source.  
For encrypted FS need `bcachefs unlock` before mounting.

**Comment by desultory** [comment]
Thanks for that info, I will try to test this soon.

One thing to consider is that ugrd does not use udev, so it would have to do something to manually bring devices online at boot time. It pulls blkid (currently 2.39.4 on gentoo), so using UUID notation for the filesystem may just be the most straightforward method.

If you want to test, you can add `bcachefs` to `binaries` in the config and set the "recovery" kernel cmdline arg to get a shell when it fails to boot.

If bcachefs says it's encrypted somewhere in the fs info under sys, it should be easy to make a simple hook that runs `bcachefs unlock` to handle decryption, and the typical uuid/partuuiid/label based mounting should be able to handle it from there.

**Comment by alexminder** [comment]
currently I can not build initramfs with ugrd:
```
ERROR    | Failed to run command: blkid /dev/sdc:/dev/sda
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/ugrd/main.py", line 158, in main
    generator.build()
  File "/usr/lib/python3.12/site-packages/ugrd/initramfs_generator.py", line 87, in build
    self.run_build()
  File "/usr/lib/python3.12/site-packages/ugrd/initramfs_generator.py", line 225, in run_build
    self.run_hook(task, force_exclude=True)
  File "/usr/lib/python3.12/site-packages/ugrd/initramfs_generator.py", line 141, in run_hook
    if function_output := self.run_func(function, *args, **kwargs):
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ugrd/initramfs_generator.py", line 103, in run_func
    if function_output := function(self):
                          ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/zenlib/util/dict_check.py", line 36, in _contains
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/zenlib/util/dict_check.py", line 36, in _contains
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ugrd/fs/mounts.py", line 491, in autodetect_root
    get_blkid_info(self, root_dev)
  File "/usr/lib/python3.12/site-packages/zenlib/util/dict_check.py", line 36, in _contains
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ugrd/fs/mounts.py", line 212, in get_blkid_info
    blkid_output = self._run(['blkid', device]).stdout.decode().strip()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ugrd/generator_helpers.py", line 157, in _run
    raise RuntimeError("Failed to run command: %s" % " ".join(cmd.args))
RuntimeError: Failed to run command: blkid /dev/sdc:/dev/sda
```

**Comment by desultory** [comment]
Ah, I think you may have to disable `hostonly` (`--no-hostonly` or `hostonly = false`) for this to work without patches. That was the main issue, I try to use blkid to get more device info for detection/validation, but blkid doesn't like that compound device notation. I could possibly just make it split off the first device and use that, but I'm not sure if there is some value in checking all devices.

**Comment by desultory** [comment]
![pic](https://github.com/user-attachments/assets/0a07e6a2-0eb4-4c71-9504-a69e8016212c)

Do you know if bcachefs supports mounting multi-device mounts with uuid? I'm only able to get it to work with paths.

I've added some stuff to the dev branch which should help with getting started testing this.

**Comment by alexminder** [comment]
> Do you know if bcachefs supports mounting multi-device mounts with uuid? I'm only able to get it to work with paths.

Yes.
what versions of tools do you use?

```console
root ~ # blkid |grep ba4e85e0-9511-487b-b8af-f89725e8dcc8
/dev/loop1: UUID="ba4e85e0-9511-487b-b8af-f89725e8dcc8" BLOCK_SIZE="512" UUID_SUB="5fa315fa-d56a-46a6-9313-0d6eb734257b" TYPE="bcachefs"
/dev/loop2: UUID="ba4e85e0-9511-487b-b8af-f89725e8dcc8" BLOCK_SIZE="512" UUID_SUB="a41d9d75-0eba-46b7-b9e9-483291e9239b" TYPE="bcachefs"

root ~ # mount -t bcachefs UUID=ba4e85e0-9511-487b-b8af-f89725e8dcc8 /mnt/bcachefs/
root ~ # df -h /mnt/bcachefs/
Filesystem             Size  Used Avail Use% Mounted on
/dev/loop1:/dev/loop2  5.5G  4.0M  5.4G   1% /mnt/bcachefs
```

in my case:
```console
root ~ # blkid -v
blkid from util-linux 2.39.4  (libblkid 2.39.4, 04-Apr-2024)
root ~ # mount -V
mount from util-linux 2.39.4 (libmount 2.39.4: selinux, btrfs, verity, namespaces, idmapping, statx, assert, debug)
root ~ # bcachefs version
1.12.0
root ~ # qlist -Iv bcachefs-tools
sys-fs/bcachefs-tools-1.13.0
```

as failback you can try to mount direct with bcachefs userspace utility:
`bcachefs mount <Device, or UUID=uuid> [mountpoint]`

**Comment by alexminder** [comment]
The issue https://github.com/systemd/systemd/issues/8234 not directly related to this, but can get some more information.

My question: does ugrd wait to all the devices comes up? With dracut we need hooks which used by `initqueue` script to report that all the devices are ready to assemble filesystem.
In my expirience, I have bcachefs rootfs on 3 different devices: 1 direct attached which use `ahci` kernel module and 2 usb attached which use `uas` kernel module. USB devices much longer initialized, but dracut can see UUID from 1st device tries to mount, get mount error and fail to boot without retry, because it use `/dev/disk/by-uuid/*` path, which does not work with bcachefs.
Besides dracut hook https://github.com/kode54/dracut-hook-bcachefs there is hook https://github.com/breavyn/dracut-bcachefs which changes device source.

**Comment by alexminder** [comment]
> I've added some stuff to the dev branch which should help with getting started testing this.

```
no_kmod: False
cpio_rotate: True
mknod_cpio: True
cpio_compression: xz
_archive_out_path: .
_cpio_archive:
check_cpio: True
check_in_cpio:
check_included_funcs: True
check_in_file:

ERROR    | No source type found in mount: {'options': {'ro'}, 'destination': PosixPath('/target_rootfs'), 'base_mount': False}
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/ugrd/main.py", line 158, in main
    generator.build()
  File "/usr/lib/python3.12/site-packages/ugrd/initramfs_generator.py", line 87, in build
    self.run_build()
  File "/usr/lib/python3.12/site-packages/ugrd/initramfs_generator.py", line 225, in run_build
    self.run_hook(task, force_exclude=True)
  File "/usr/lib/python3.12/site-packages/ugrd/initramfs_generator.py", line 141, in run_hook
    if function_output := self.run_func(function, *args, **kwargs):
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ugrd/initramfs_generator.py", line 103, in run_func
    if function_output := function(self):
                          ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ugrd/fs/mounts.py", line 717, in export_mount_info
    self["exports"]["MOUNTS_ROOT_SOURCE"] = _get_mount_str(self, self["mounts"]["root"])
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ugrd/fs/mounts.py", line 151, in _get_mount_str
    mount_type, mount_name = _get_mount_source_type(self, mount, with_val=True)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ugrd/fs/mounts.py", line 144, in _get_mount_source_type
    raise ValueError("No source type found in mount: %s" % mount)
ValueError: No source type found in mount: {'options': {'ro'}, 'destination': PosixPath('/target_rootfs'), 'base_mount': False}
```

**Comment by alexminder** [comment]
there is some more error related with musl libc:

```INFO     | Build directory does not exist, skipping cleaning: /tmp/initramfs_build
ERROR    | Failed to run command: ldconfig -p
ERROR    | Command output:

ERROR    | Command error:
Unimplemented option: -p

CRITICAL | Unable to run ldconfig -p, if GCC is being used, this is fatal
```

musl provides `ldconfig` as script which does not have `-p` option:

`/usr/sbin/ldconfig`:
```bash
...
get_options() {
        LDSO_CONF=""
        while getopts "vnNXf:C:r:p" opt "$@"; do
                case $opt in
                v)
                        echo "ldconfig for musl in Gentoo"
                        VERBOSE=1
                        ;;
                r)
                        ROOT=${OPTARG}
                        ;;
                f)
                        LDSO_CONF=${OPTARG}
                        ;;
                X)
                        UPDATE_LINKS=0
                        ;;
                \?)
                        echo "Invalid option: -${opt}" >&2
                        exit 1
                        ;;
                n|N|C|p)
                        echo "Unimplemented option: -${opt}" >&2
                        exit 1
                        ;;
                esac
        done
        if [[ -z ${LDSO_CONF} ]]; then
                LDSO_CONF=${ROOT}${EPREFIX}${LDSO_CONF_FILE}
        fi

        if [[ ${UPDATE_LINKS} == 1 ]]; then
                echo "Updating links is not implemented."
        fi
}
...
```

**Comment by alexminder** [comment]
I have tried to boot from `dev` branch and got same result.

Note, it tries to mount different devices.


![IMG_20241022_135855_682.jpg](https://github.com/user-attachments/assets/d6117c5a-7b80-42b1-aa1e-c947bc0a84b0)

**Comment by desultory** [comment]
> there is some more error related with musl libc:
> 
> ```
> ERROR    | Failed to run command: ldconfig -p
> ERROR    | Command output:
> 
> ERROR    | Command error:
> Unimplemented option: -p
> 
> CRITICAL | Unable to run ldconfig -p, if GCC is being used, this is fatal
> ```
> 
> musl provides `ldconfig` as script which does not have `-p` option:
> 
> `/usr/sbin/ldconfig`:
> 
> ```shell
> ...
> get_options() {
>         LDSO_CONF=""
>         while getopts "vnNXf:C:r:p" opt "$@"; do
>                 case $opt in
>                 v)
>                         echo "ldconfig for musl in Gentoo"
>                         VERBOSE=1
>                         ;;
>                 r)
>                         ROOT=${OPTARG}
>                         ;;
>                 f)
>                         LDSO_CONF=${OPTARG}
>                         ;;
>                 X)
>                         UPDATE_LINKS=0
>                         ;;
>                 \?)
>                         echo "Invalid option: -${opt}" >&2
>                         exit 1
>                         ;;
>                 n|N|C|p)
>                         echo "Unimplemented option: -${opt}" >&2
>                         exit 1
>                         ;;
>                 esac
>         done
>         if [[ -z ${LDSO_CONF} ]]; then
>                 LDSO_CONF=${ROOT}${EPREFIX}${LDSO_CONF_FILE}
>         fi
> 
>         if [[ ${UPDATE_LINKS} == 1 ]]; then
>                 echo "Updating links is not implemented."
>         fi
> }
> ...
> ```

Yes, this "critical" is mostly visual, there is a toggle to not look for glibc, but it warns otherwise.


> I have tried to boot from `dev` branch and got same result.
> 
> Note, it tries to mount different devices.
> 
> ![IMG_20241022_135855_682.jpg](https://private-user-images.githubusercontent.com/15701425/378816401-d6117c5a-7b80-42b1-aa1e-c947bc0a84b0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1OTY0ODUsIm5iZiI6MTcyOTU5NjE4NSwicGF0aCI6Ii8xNTcwMTQyNS8zNzg4MTY0MDEtZDYxMTdjNWEtN2I4MC00MmIxLWFhMWUtYzk0N2JjMGE4NGIwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDExMjMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmODJiYWIzNjMxZWIzNjhmZTFmODQ5ZGE3OTk3M2Y3ZWEzMDRjODliZDA0MjliMDhlYjUyODYzZmQyY2Q4Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wX2WRgCg4TOjmV1LTx1wCIyhaQcygP_VlS1jWhbR0H8)

Yes, this was the issue I'm facing. For multi-device filesystems, you seemingly MUST mount by `/dev/dev1:/dev/dev2` or similar, I don't know how you can mount by UUID if that is possible.

From that branch, you should be able to use the recovery console to manually mount it, you can do like `servar MOUNTS_ROOT_SOURCE "/dev/sda1:/dev/sdb1"` or whatever works for your system. If I make this work using paths, I will need to make a bash function which resolves those from the UUID or something. I just really do not like this method.

**Comment by alexminder** [comment]
> I have tried to boot from `dev` branch and got same result.

It seems there is no mount helper in initramfs exists: `mount.bcachefs`. It should be link to bcachefs binary. Without helper it use one device and kernel syscall.

**Comment by alexminder** [comment]
I'm trying to add mount helper and with `binaries` section. At host system it links to `/usr/bin`, but you put `bcachefs` to `/usr/sbin`. So this workaround dows not work.
```console
-rwxr-xr-x   2 root     root      3367240 Oct 18 09:17 usr/sbin/bcachefs
lrwxrwxrwx   1 root     root           18 Oct 18 09:17 usr/sbin/mount.bcachefs -> /usr/bin/bcachefs
```

Can you add correct symlink with appropriate module?

**Comment by desultory** [comment]
> I'm trying to add mount helper and with `binaries` section. At host system it links to `/usr/sbin`, but you put `bcachefs` to `/usr/bin`. `binaries = ['/usr/sbin/mount.bcachefs','/usr/sbin/bcachefs']` puts in both places and I got warning:
> 
> ```
> WARNING  | [usr/bin/bcachefs] Hash matches existing entry: usr/sbin/bcachefs
> WARNING  | [usr/bin/bcachefs] Setting filesize to 0
> ```
> 
> Can you add correct symlink with appropriate module?

for binaries you don't use the absolute path, it resolves it from the PATHS defined in the environment where it was run

**Comment by alexminder** [comment]
> You should be able to do mount -t bcachefs or possibly use the bcachefs binary directly

Without `mount.bcachefs` it does not works. You can notice it in my screenshot. 

> This is in the dev branch and should be automatically activated if a bcachefs mount is configured:

`bcachefs` binary not enough. `mount.bcachefs` symlink should be added  to initramfs.

**Comment by desultory** [comment]
> > You should be able to do mount -t bcachefs or possibly use the bcachefs binary directly
> 
> Without `mount.bcachefs` it does not works. You can notice it in my screenshot.
> 
I was able to do something like `setvar MOUNTS_ROOT_SOURCE "/dev/vdb1:/dev/vdc1"` and then exit the shell and it worked. That makes it eventually run `mount -t bcachefs /dev/vdb1:/dev/vbc1 /target_rootfs` which works.

> > This is in the dev branch and should be automatically activated if a bcachefs mount is configured:
> 
> `bcachefs` binary not enough. `mount.bcachefs` symlink should be added to initramfs.

You're able to manually define a symlink, but it won't end up running `mount.bcachefs` as it is. ugrd passes -t to mounts to be more generic. 
https://github.com/desultory/ugrd/blob/main/docs/configuration.md#symlink-creation

**Comment by alexminder** [comment]
```console
# strace mount -vvv -t bcachefs UUID=ba4e85e0-9511-487b-b8af-f89725e8dcc8 /mnt/bcachefs/ 2>&1|grep mount.bcachef
statx(AT_FDCWD, "/sbin/mount.bcachefs", AT_STATX_DONT_SYNC|AT_NO_AUTOMOUNT, STATX_TYPE|STATX_MODE|STATX_INO, {stx_mask=STATX_BASIC_STATS|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0755, stx_size=3194568, ...}) = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0xe9421fd0b90) = 1403669
wait4(1403669, [INFO  src/commands/mount.rs:303] mounting with params: device: /dev/loop1:/dev/loop2, target: /mnt/bcachefs, options: rw
[INFO  src/commands/mount.rs:43] mounting filesystem
[{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 1403669
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=1403669, si_uid=0, si_status=0, si_utime=0, si_stime=2 /* 0.02 s */} ---
# ls -l /sbin/mount.bcachefs
lrwxrwxrwx. 1 root root 8 Oct 18 20:56 /sbin/mount.bcachefs -> bcachefs
```
As you can see generic mount calls mount helper `mount.bcachefs` which is bcachefs binary usespace utility. If you add symlynk in to initramfs boot with UUID should works.

**Comment by desultory** [comment]
![pic](https://github.com/user-attachments/assets/70cfba2f-51c8-47ac-800a-c88616143354)
Adding a symlink didn't seem to help. You can do that by simply adding `mount.bcachefs` to `binaries`

**Comment by desultory** [comment]
I think this is related to udev not being used here, bcachefs seems to require that for multi-device mounts. I'm hoping bcachefs can support this without udev, otherwise I will have to make something that gets device paths from blkid output

**Comment by alexminder** [comment]
mount helper bcachefs binary honor BCACHEFS_BLOCK_SCAN variable to scan for devices.

More info here: https://github.com/koverstreet/bcachefs-tools/issues/308#issuecomment-2437169898

**Comment by alexminder** [comment]
> I think this is related to udev not being used here, bcachefs seems to require that for multi-device mounts. I'm hoping bcachefs can support this without udev, otherwise I will have to make something that gets device paths from blkid output

@desultory, Can [BCACHEFS_LOG=trace](https://github.com/koverstreet/bcachefs-tools/pull/309) help to debug?

**Comment by desultory** [comment]
> > I think this is related to udev not being used here, bcachefs seems to require that for multi-device mounts. I'm hoping bcachefs can support this without udev, otherwise I will have to make something that gets device paths from blkid output
> 
> @desultory, Can [BCACHEFS_LOG=trace](https://github.com/koverstreet/bcachefs-tools/pull/309) help to debug?

Maybe, have you tried testing this? It seems like bcachefs tools want udev, and it will potentially be unsafe to try to use them without udev.

**Comment by alexminder** [comment]
So, about `libgcc_s.so.1` : glibc uses `/etc/ld.so.cache` to find libraries.
I think you should  put `${TMP_INITRD_BUILD_DIR}/etc/ld.so.conf` and generate a cache file at initramfs build time, like `ldconfig -C ${TMP_INITRD_BUILD_DIR}` .

About UUID, it seems that it requires udev. Without udev, only device names (for example, /dev/sda:/dev/sdb) can be used, which can be found with blkid. Can you add such logic?

**Comment by desultory** [comment]
> So, about `libgcc_s.so.1` : glibc uses `/etc/ld.so.cache` to find libraries. I think you should put `${TMP_INITRD_BUILD_DIR}/etc/ld.so.conf` and generate a cache file at initramfs build time, like `ldconfig -C ${TMP_INITRD_BUILD_DIR}` .
> 

Is this related to the current issue, or another one? How would this work with musl?

> About UUID, it seems that it requires udev. Without udev, only device names (for example, /dev/sda:/dev/sdb) can be used, which can be found with blkid. Can you add such logic?

It's possible to add that logic, just not simple and this seems like something which should be handled by the bcachefs mount util (like most other filesystems). Without udev something would need to "resolve" the uuids. Both blkid and lsblk are included by default so this shouldn't be impossible, just not as simple as it should be (imo)

**Comment by alexminder** [comment]
@desultory 

> Is this related to the current issue, or another one? How would this work with musl?

Yes, in the comment https://github.com/desultory/ugrd/issues/84#issuecomment-2429729453 you post screenshots with libgcc search problem. 
Musl libc have same behaviour. All the required paths should be described in the `/etc/ld.so.conf` and `ldconfig` generates `/etc/ld-musl-x86_64.path` which used by musl libc to find libraries. This is a plain text file, in contrast to glibc which uses a binary format. `ldconfig` is not part of musl libc, but gentoo ships it with the package as addition.

> Both blkid and lsblk are included by default so this shouldn't be impossible, just not as simple as it should be (imo)

lsblk nothing shows under ugrd recovery shell. Only with blkid I can saw UUIDs of devices.

**Comment by desultory** [comment]
I may try to test this a bit more in the v2 branch, im trying to make the build environment much more consistent, and will look into this. I'm hoping much more consistent symlinking and the ability to order init functions more dynamically may make it easier to handle different mount setups, and could help here.

**Comment by desultory** [comment]
the symlinks and whatnot did not help. I'm wondering why this is only an issue with bcachefs, and mount.bcachefs works while mount -t bcachefs does not.

maybe more LD_LIBRARY_PATH's should be set?

**Comment by desultory** [comment]
https://github.com/desultory/ugrd/pull/300 I think this partially fixes some of the bcachefs issues

I'm still not able to get it to work without udev:

![Image](https://github.com/user-attachments/assets/4700e607-08c7-49f7-a00c-bde6f3019a08)

**Comment by desultory** [comment]
> Maybe then it makes sense to add logic for checking multiple devices? Something like
> 
> # blkid |grep 91eabf39-c438-4819-98db-d306dcb40afd
> /dev/sdb: UUID="91eabf39-c438-4819-98db-d306dcb40afd" LABEL="root" BLOCK_SIZE="4096" UUID_SUB="0ad003eb-c1b8-43f7-bb44-18f511765cd0" TYPE="bcachefs"
> /dev/sda2: UUID="91eabf39-c438-4819-98db-d306dcb40afd" LABEL="root" BLOCK_SIZE="4096" UUID_SUB="1599ef77-4887-4978-b2f1-2e97d8feca0a" TYPE="bcachefs" PARTLABEL="Linux x86-64 root (/)" PARTUUID="c60fe909-8a7e-48f8-ba21-f1cd9d98bdb4"

maybe, I'd like to just try to tell it that udev shouldn't be used so it can enumerate multiple devices itself. that way it can just get a uuid passed to it like any other fs type.

were the other changes helpful at all? I think it should fix some of the other underlying issues, still not sure how to convince it to work without udev though

**Comment by alexminder** [comment]
Right now, bcachefs-tools scans devices only when the `BCACHEFS_BLOCK_SCAN` environment variable is present and uses udev for this, just like `lsblk -f` does. They look at `/run/udev/data` that should be filled with `udevd` (`udeadm triggers`). https://github.com/koverstreet/bcachefs-tools/blob/master/src/commands/mount.rs#L143 .
If udev is missing, the device scan will not work. In such case you will need to implement your own device search engine and pass this list to bcachefs for mounting. Can you implement such hack for bcachefs?

**Comment by alexminder** [comment]
Thanks. it works with default config

boot log:
```
 * INFO: UGRD v2.1.0
 * INFO: Built for kernel version: 6.18.7-gentoo-dist-hardened
 * INFO: Loading kernel modules: bcachefs virtio_scsi vmw_vmci lpc_ich
insmod /lib/modules/6.18.7-gentoo-dist-hardened/kernel/lib/lz4/lz4hc_compress.ko
insmod /lib/modules/6.18.7-gentoo-dist-hardened/kernel/lib/lz4/lz4_compress.ko
insmod /lib/modules/6.18.7-gentoo-dist-hardened/extra/bcachefs.ko
[   51.630040] bcachefs: loading out-of-tree module taints kernel.
insmod /lib/modules/6.18.7-gentoo-dist-hardened/kernel/drivers/scsi/virtio_scsi.ko
[   51.911695] sd 6:0:0:3: Power-on or device reset occurred
[   51.914501] sd 6:0:0:4: Power-on or device reset occurred
[   51.915407] sd 6:0:0:5: Power-on or device reset occurred
insmod /lib/modules/6.18.7-gentoo-dist-hardened/kernel/drivers/misc/vmw_vmci/vmw_vmci.ko
insmod /lib/modules/6.18.7-gentoo-dist-hardened/kernel/drivers/mfd/lpc_ich.ko
 * INFO: Mounting root partition based on /proc/cmdline: UUID=54d50843-d5c8-4876-aaf5-a36a0296b775 -t bcachefs -o x-systemd.requires=/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-0-3,x-systemd.requires=/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-0-4,x-systemd.mount-timeout=300,x-systemd.after=systemd-udevd.service,x-systemd.after=systemd-udev-trigger.service
 * INFO: Checking root mount: /target_rootfs
 * INFO: Switching root to: /target_rootfs /usr/lib/systemd/systemd
[   52.223699] [UGRD 2.1.0] Running init: /usr/lib/systemd/systemd
 * INFO: Cleaning up /run/ugrd
```

**Comment by desultory** [comment]
https://github.com/koverstreet/bcachefs-tools/issues/344

it seems udev won't be needed in future releases, i have not tested but this seems like it should mean udev isn't absolutely required
